Add config to change settings.DEBUG
YunoHost-Apps/django-fritzconnection_ynh pull request #18
Opened 2022-05-18 16:18 UTC by jedie

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-05-19 07:07 UTC, jedie commented
!testme

2022-05-25 08:47 UTC, zamentur requested changes

2022-05-25 08:47 UTC, zamentur commented on config_panel.toml
> +        bind = "DJANGO_DEBUG:/opt/yunohost/__APP__/local_settings.py"
The variable in local_settings.py that you want to change is name DEBUG, not DJANGO_DEBUG (DJANGO_DEBUG is your bash var durint install/upgrade operation)
```suggestion
        bind = "DEBUG:/opt/yunohost/__APP__/local_settings.py"
```

2022-08-16 07:50 UTC, jedie commented
reworked in https://github.com/YunoHost-Apps/django-fritzconnection_ynh/pull/20

2022-08-16 07:50 UTC, closed without merging